// 65+ distinct meals across 8 demonstration kitchens and 20 categories

export const SEED_MEALS = [
  // 1. Breakfast (cat_01)
  {
    id: 'meal_001',
    seller_id: 'seller_03',
    category_id: 'cat_01',
    name: 'Kanda Poha with Roasted Peanuts',
    slug: 'kanda-poha-roasted-peanuts',
    description: 'Fluffy flattened rice tempered with mustard seeds, curry leaves, crunchy roasted peanuts, turmeric, and fresh lemon juice.',
    cuisine: 'Maharashtrian',
    base_price: 79.00,
    portion_choices: ['Regular (250g)', 'Hearty (350g)'],
    ingredients: ['Flattened Rice', 'Peanuts', 'Onion', 'Curry Leaves', 'Green Chilies', 'Lemon', 'Mustard Seeds'],
    allergens: ['Peanuts'],
    dietary_tags: ['Vegetarian', 'Breakfast'],
    is_available: true,
    is_featured: true,
    is_tiffin_eligible: true,
    prep_time_minutes: 15,
    calories: 290,
    protein_grams: 6.5,
    carbs_grams: 48.0,
    fat_grams: 7.2,
    image_url: '/images/meals/meal_001.jpg',
    rating: 4.8,
    rating_count: 85
  },
  {
    id: 'meal_002',
    seller_id: 'seller_04',
    category_id: 'cat_01',
    name: 'Steamed Rava Idli with Sambar & Chutney',
    slug: 'steamed-rava-idli-sambar',
    description: 'Four soft, pillowy semolina idlis with vegetable-loaded piping hot lentil sambar and freshly ground coconut-mint chutney.',
    cuisine: 'South Indian',
    base_price: 89.00,
    portion_choices: ['4 Pieces', '6 Pieces'],
    ingredients: ['Semolina', 'Curd', 'Mustard Seeds', 'Lentils', 'Drumsticks', 'Grated Coconut'],
    allergens: ['Gluten', 'Dairy'],
    dietary_tags: ['Vegetarian', 'Breakfast'],
    is_available: true,
    is_featured: true,
    is_tiffin_eligible: true,
    prep_time_minutes: 15,
    calories: 310,
    protein_grams: 8.0,
    carbs_grams: 52.0,
    fat_grams: 5.0,
    image_url: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    rating_count: 140
  },
  {
    id: 'meal_003',
    seller_id: 'seller_04',
    category_id: 'cat_01',
    name: 'Vegetable Upma with Filter Coffee Combo',
    slug: 'vegetable-upma-combo',
    description: 'Traditional roasted semolina upma cooked with carrots, green peas, curry leaves, and ginger. Served with spicy tomato chutney.',
    cuisine: 'South Indian',
    base_price: 85.00,
    portion_choices: ['Regular (300g)'],
    ingredients: ['Semolina', 'Carrot', 'Green Peas', 'Ginger', 'Curry Leaves', 'Ghee'],
    allergens: ['Gluten', 'Dairy'],
    dietary_tags: ['Vegetarian', 'Breakfast'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: true,
    prep_time_minutes: 20,
    calories: 320,
    protein_grams: 7.2,
    carbs_grams: 54.0,
    fat_grams: 6.5,
    image_url: '/images/meals/meal_003.jpg',
    rating: 4.6,
    rating_count: 62
  },
  {
    id: 'meal_004',
    seller_id: 'seller_01',
    category_id: 'cat_01',
    name: 'Desi Paneer Bhurji with 3 Multigrain Phulkas',
    slug: 'paneer-bhurji-multigrain-phulka',
    description: 'Crumbled fresh paneer sautéed with finely chopped onions, juicy tomatoes, capsicum, and fresh coriander. Served with 3 soft phulkas.',
    cuisine: 'North Indian',
    base_price: 139.00,
    portion_choices: ['Standard (3 Rotis)', 'Hearty (4 Rotis)'],
    ingredients: ['Fresh Paneer', 'Onion', 'Tomato', 'Capsicum', 'Multigrain Flour', 'Coriander'],
    allergens: ['Dairy', 'Gluten'],
    dietary_tags: ['Vegetarian', 'High-Protein', 'Breakfast'],
    is_available: true,
    is_featured: true,
    is_tiffin_eligible: true,
    prep_time_minutes: 20,
    calories: 460,
    protein_grams: 24.5,
    carbs_grams: 44.0,
    fat_grams: 18.0,
    image_url: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    rating_count: 110
  },
  {
    id: 'meal_005',
    seller_id: 'seller_05',
    category_id: 'cat_01',
    name: 'Rolled Oats & Chia Power Bowl with Berries',
    slug: 'oats-chia-power-bowl',
    description: 'Slow-cooked whole rolled oats in almond milk, topped with chia seeds, roasted almonds, seasonal berries, and raw forest honey.',
    cuisine: 'Continental',
    base_price: 149.00,
    portion_choices: ['350ml Bowl'],
    ingredients: ['Rolled Oats', 'Almond Milk', 'Chia Seeds', 'Blueberries', 'Almonds', 'Honey'],
    allergens: ['Nuts'],
    dietary_tags: ['Vegetarian', 'Vegan', 'Breakfast'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: false,
    prep_time_minutes: 10,
    calories: 340,
    protein_grams: 12.0,
    carbs_grams: 58.0,
    fat_grams: 7.5,
    image_url: '/images/meals/meal_005.jpg',
    rating: 4.7,
    rating_count: 94
  },

  // 2. Everyday Tiffins (cat_02)
  {
    id: 'meal_006',
    seller_id: 'seller_01',
    category_id: 'cat_02',
    name: 'Classic Daily Homestyle Tiffin Dabba',
    slug: 'classic-daily-homestyle-tiffin',
    description: 'Comfort in a dabba: 4 phulkas, comforting yellow dal tadka, seasonal dry sabzi (aloo beans), steamed basmati rice, and homemade salad.',
    cuisine: 'North Indian',
    base_price: 120.00,
    portion_choices: ['Standard Tiffin', 'Large Tiffin (+₹30)'],
    ingredients: ['Wheat Flour', 'Toor Dal', 'French Beans', 'Potato', 'Basmati Rice', 'Cumin'],
    allergens: ['Gluten'],
    dietary_tags: ['Vegetarian', 'Everyday Tiffins'],
    is_available: true,
    is_featured: true,
    is_tiffin_eligible: true,
    prep_time_minutes: 25,
    calories: 520,
    protein_grams: 16.5,
    carbs_grams: 86.0,
    fat_grams: 10.5,
    image_url: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    rating_count: 320
  },
  {
    id: 'meal_007',
    seller_id: 'seller_01',
    category_id: 'cat_02',
    name: 'Special Paneer Subzi Tiffin Meal',
    slug: 'special-paneer-tiffin-meal',
    description: '4 ghee phulkas, rich paneer shimla mirch masala, slow-simmered dal fry, jeera rice, fresh cucumber salad, and roasted papad.',
    cuisine: 'North Indian',
    base_price: 155.00,
    portion_choices: ['Standard (4 Phulkas)', 'Mega (5 Phulkas + Extra Dal)'],
    ingredients: ['Paneer', 'Capsicum', 'Toor Dal', 'Wheat Flour', 'Jeera Rice', 'Ghee'],
    allergens: ['Dairy', 'Gluten'],
    dietary_tags: ['Vegetarian', 'Everyday Tiffins'],
    is_available: true,
    is_featured: true,
    is_tiffin_eligible: true,
    prep_time_minutes: 25,
    calories: 630,
    protein_grams: 22.0,
    carbs_grams: 88.0,
    fat_grams: 18.5,
    image_url: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    rating_count: 210
  },
  {
    id: 'meal_008',
    seller_id: 'seller_03',
    category_id: 'cat_02',
    name: 'Gharche Jevan Maharashtrian Tiffin',
    slug: 'gharche-jevan-maharashtrian-tiffin',
    description: '3 warm wheat chapatis, batata rassa bhaaji, fragrant varan bhat with a drizzle of desi ghee, methi koshimbir, and lemon wedge.',
    cuisine: 'Maharashtrian',
    base_price: 125.00,
    portion_choices: ['Standard Tiffin', 'Double Chapati (+₹20)'],
    ingredients: ['Whole Wheat Flour', 'Potato', 'Toor Dal', 'Rice', 'Fenugreek', 'Peanuts', 'Ghee'],
    allergens: ['Gluten', 'Dairy'],
    dietary_tags: ['Vegetarian', 'Everyday Tiffins'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: true,
    prep_time_minutes: 25,
    calories: 540,
    protein_grams: 15.0,
    carbs_grams: 90.0,
    fat_grams: 11.0,
    image_url: '/images/meals/meal_008.jpg',
    rating: 4.8,
    rating_count: 145
  },
  {
    id: 'meal_009',
    seller_id: 'seller_04',
    category_id: 'cat_02',
    name: 'Dakshin Meals Tiffin Carrier',
    slug: 'dakshin-meals-tiffin-carrier',
    description: 'Steamed Sona Masoori rice, spiced drumstick sambar, rasam, cabbage poriyal with grated coconut, curd rice, and lemon pickle.',
    cuisine: 'South Indian',
    base_price: 115.00,
    portion_choices: ['Regular 3-Tier Dabba'],
    ingredients: ['Sona Masoori Rice', 'Lentils', 'Drumstick', 'Cabbage', 'Coconut', 'Curd'],
    allergens: ['Dairy'],
    dietary_tags: ['Vegetarian', 'Everyday Tiffins'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: true,
    prep_time_minutes: 20,
    calories: 490,
    protein_grams: 14.5,
    carbs_grams: 88.0,
    fat_grams: 8.0,
    image_url: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    rating_count: 180
  },

  // 3. North Indian (cat_03)
  {
    id: 'meal_010',
    seller_id: 'seller_02',
    category_id: 'cat_03',
    name: 'Dhaba Style Rajma Masala & Jeera Rice',
    slug: 'rajma-masala-jeera-rice',
    description: 'Overnight soaked Kashmiri rajma simmered in an aromatic onion, ginger, garlic, and tomato reduction. Served over fragrant cumin rice.',
    cuisine: 'North Indian',
    base_price: 135.00,
    portion_choices: ['Single Bowl (450g)', 'Mega Bowl (650g)'],
    ingredients: ['Red Kidney Beans', 'Basmati Rice', 'Onion', 'Tomato', 'Cumin', 'Ginger', 'Garlic'],
    allergens: [],
    dietary_tags: ['Vegetarian', 'Vegan', 'North Indian'],
    is_available: true,
    is_featured: true,
    is_tiffin_eligible: true,
    prep_time_minutes: 20,
    calories: 490,
    protein_grams: 18.0,
    carbs_grams: 84.0,
    fat_grams: 7.5,
    image_url: '/images/meals/meal_010.jpg',
    rating: 4.8,
    rating_count: 290
  },
  {
    id: 'meal_011',
    seller_id: 'seller_02',
    category_id: 'cat_03',
    name: 'Amritsari Chole Chawal with Sirka Onion',
    slug: 'amritsari-chole-chawal',
    description: 'Dark, spice-infused Punjabi kabuli chana simmered with whole spices, dry pomegranate seeds, and fresh coriander. Served with steamed basmati rice.',
    cuisine: 'North Indian',
    base_price: 139.00,
    portion_choices: ['Standard Box', 'Large Box'],
    ingredients: ['Chickpeas', 'Tea Leaves', 'Anardana', 'Basmati Rice', 'Onion', 'Green Chili'],
    allergens: [],
    dietary_tags: ['Vegetarian', 'Vegan', 'North Indian'],
    is_available: true,
    is_featured: true,
    is_tiffin_eligible: true,
    prep_time_minutes: 20,
    calories: 510,
    protein_grams: 17.5,
    carbs_grams: 86.0,
    fat_grams: 8.5,
    image_url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    rating_count: 245
  },
  {
    id: 'meal_012',
    seller_id: 'seller_02',
    category_id: 'cat_03',
    name: 'Dal Makhani Slow-Simmered with 3 Butter Rotis',
    slug: 'dal-makhani-butter-roti',
    description: 'Creamy black lentils and red kidney beans slow-cooked on coal fire for 12 hours with fresh butter and cream. Served with 3 whole wheat butter rotis.',
    cuisine: 'North Indian',
    base_price: 169.00,
    portion_choices: ['Standard (3 Rotis)', 'Hearty (4 Rotis)'],
    ingredients: ['Black Urad Dal', 'Rajma', 'Butter', 'Cream', 'Tomato Puree', 'Wheat Flour'],
    allergens: ['Dairy', 'Gluten'],
    dietary_tags: ['Vegetarian', 'North Indian'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: true,
    prep_time_minutes: 25,
    calories: 620,
    protein_grams: 19.0,
    carbs_grams: 74.0,
    fat_grams: 24.0,
    image_url: '/images/meals/meal_012.jpg',
    rating: 4.9,
    rating_count: 360
  },
  {
    id: 'meal_013',
    seller_id: 'seller_02',
    category_id: 'cat_03',
    name: 'Palak Paneer with Jeera Rice Bowl',
    slug: 'palak-paneer-jeera-rice',
    description: 'Blanched spinach puree tempered with garlic and kasuri methi, gently cooked with tender paneer cubes. Accompanied by fragrant cumin rice.',
    cuisine: 'North Indian',
    base_price: 159.00,
    portion_choices: ['Single Bowl (450g)'],
    ingredients: ['Spinach', 'Paneer', 'Garlic', 'Basmati Rice', 'Cumin', 'Fenugreek Leaves'],
    allergens: ['Dairy'],
    dietary_tags: ['Vegetarian', 'North Indian'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: true,
    prep_time_minutes: 20,
    calories: 520,
    protein_grams: 21.0,
    carbs_grams: 58.0,
    fat_grams: 18.0,
    image_url: '/images/meals/meal_013.jpg',
    rating: 4.7,
    rating_count: 175
  },

  // 4. South Indian (cat_04)
  {
    id: 'meal_014',
    seller_id: 'seller_04',
    category_id: 'cat_04',
    name: 'Mysore Masala Dosa with Sambar & 2 Chutneys',
    slug: 'mysore-masala-dosa',
    description: 'Crisp golden fermented rice crepe slathered with fiery red garlic-chili chutney, stuffed with spiced potato mash, served with lentil sambar.',
    cuisine: 'South Indian',
    base_price: 110.00,
    portion_choices: ['Single Dosa', '2 Dosas Combo'],
    ingredients: ['Rice', 'Urad Dal', 'Red Chili', 'Garlic', 'Potato', 'Curry Leaves', 'Ghee'],
    allergens: ['Dairy'],
    dietary_tags: ['Vegetarian', 'South Indian'],
    is_available: true,
    is_featured: true,
    is_tiffin_eligible: false,
    prep_time_minutes: 20,
    calories: 440,
    protein_grams: 9.5,
    carbs_grams: 68.0,
    fat_grams: 14.0,
    image_url: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    rating_count: 310
  },
  {
    id: 'meal_015',
    seller_id: 'seller_04',
    category_id: 'cat_04',
    name: 'Tempered Curd Rice (Thayir Sadam) with Pomegranate',
    slug: 'tempered-curd-rice-pomegranate',
    description: 'Cooling probiotic rice mashed with velvety thick curd, tempered with mustard seeds, green chilies, ginger, curry leaves, and pomegranate arils.',
    cuisine: 'South Indian',
    base_price: 99.00,
    portion_choices: ['Standard (350g)'],
    ingredients: ['Sona Masoori Rice', 'Fresh Curd', 'Mustard Seeds', 'Curry Leaves', 'Ginger', 'Pomegranate'],
    allergens: ['Dairy'],
    dietary_tags: ['Vegetarian', 'South Indian'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: true,
    prep_time_minutes: 10,
    calories: 360,
    protein_grams: 10.0,
    carbs_grams: 56.0,
    fat_grams: 9.5,
    image_url: '/images/meals/meal_015.jpg',
    rating: 4.8,
    rating_count: 140
  },
  {
    id: 'meal_016',
    seller_id: 'seller_04',
    category_id: 'cat_04',
    name: 'Bisi Bele Bath with Boondi & Ghee',
    slug: 'bisi-bele-bath-boondi',
    description: 'Classic Karnataka spiced rice-lentil stew cooked with tamarind, jaggery, mixed vegetables, and a spoonful of pure cow ghee. Topped with spiced boondi.',
    cuisine: 'South Indian',
    base_price: 119.00,
    portion_choices: ['Regular (400g)'],
    ingredients: ['Rice', 'Toor Dal', 'French Beans', 'Carrot', 'Tamarind', 'Bisi Bele Bath Masala', 'Ghee'],
    allergens: ['Dairy', 'Gluten'],
    dietary_tags: ['Vegetarian', 'South Indian'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: true,
    prep_time_minutes: 20,
    calories: 480,
    protein_grams: 14.0,
    carbs_grams: 74.0,
    fat_grams: 12.0,
    image_url: '/images/meals/meal_016.jpg',
    rating: 4.7,
    rating_count: 115
  },

  // 5. Maharashtrian (cat_05)
  {
    id: 'meal_017',
    seller_id: 'seller_03',
    category_id: 'cat_05',
    name: 'Kolhapuri Spiced Misal Pav (2 Pavs)',
    slug: 'kolhapuri-misal-pav',
    description: 'Fiery sprouted moth bean curry simmered with authentic Kolhapuri masala, topped with farsan, diced onions, and fresh lemon. Served with 2 soft pavs.',
    cuisine: 'Maharashtrian',
    base_price: 115.00,
    portion_choices: ['2 Pavs', '4 Pavs Combo'],
    ingredients: ['Moth Bean Sprouts', 'Kolhapuri Chili', 'Farsan', 'Onion', 'Pav Bread', 'Lemon'],
    allergens: ['Gluten'],
    dietary_tags: ['Vegetarian', 'Maharashtrian'],
    is_available: true,
    is_featured: true,
    is_tiffin_eligible: false,
    prep_time_minutes: 20,
    calories: 490,
    protein_grams: 15.0,
    carbs_grams: 72.0,
    fat_grams: 14.5,
    image_url: '/images/meals/meal_017.jpg',
    rating: 4.9,
    rating_count: 260
  },
  {
    id: 'meal_018',
    seller_id: 'seller_03',
    category_id: 'cat_05',
    name: 'Pithla Bhakri Thali with Thecha',
    slug: 'pithla-bhakri-thecha',
    description: 'Rustic gram flour curry tempered with garlic and cumin, served with 2 warm jowar bhakris, fiery green chili-garlic thecha, and raw onion rings.',
    cuisine: 'Maharashtrian',
    base_price: 135.00,
    portion_choices: ['Standard Thali (2 Bhakris)'],
    ingredients: ['Gram Flour (Besan)', 'Jowar Flour', 'Green Chilies', 'Garlic', 'Mustard Seeds'],
    allergens: [],
    dietary_tags: ['Vegetarian', 'Vegan', 'Maharashtrian'],
    is_available: true,
    is_featured: true,
    is_tiffin_eligible: true,
    prep_time_minutes: 25,
    calories: 460,
    protein_grams: 16.5,
    carbs_grams: 78.0,
    fat_grams: 9.0,
    image_url: '/images/meals/meal_018.jpg',
    rating: 4.8,
    rating_count: 155
  },
  {
    id: 'meal_019',
    seller_id: 'seller_03',
    category_id: 'cat_05',
    name: 'Varan Bhat with Desi Ghee & Batata Sukka',
    slug: 'varan-bhat-batata-sukka',
    description: 'Ultimate Maharashtrian comfort: Steamed Indrayani rice topped with thick, simple toor dal varan, dollop of A2 cow ghee, and dry spiced potato sabzi.',
    cuisine: 'Maharashtrian',
    base_price: 119.00,
    portion_choices: ['Regular (400g)'],
    ingredients: ['Indrayani Rice', 'Toor Dal', 'A2 Ghee', 'Potato', 'Mustard Seeds', 'Turmeric'],
    allergens: ['Dairy'],
    dietary_tags: ['Vegetarian', 'Maharashtrian'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: true,
    prep_time_minutes: 20,
    calories: 450,
    protein_grams: 13.5,
    carbs_grams: 74.0,
    fat_grams: 10.0,
    image_url: 'https://images.unsplash.com/photo-1596560548464-f010549b84d7?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    rating_count: 190
  },

  // 6. High-Protein Meals (cat_06)
  {
    id: 'meal_020',
    seller_id: 'seller_05',
    category_id: 'cat_06',
    name: 'Grilled Herb Paneer Macro Bowl (32g Protein)',
    slug: 'grilled-paneer-macro-bowl',
    description: 'Pan-seared malai paneer cubes marinated in rosemary, oregano, and olive oil, served over quinoa and steamed broccoli with lemon tahini dressing.',
    cuisine: 'Continental',
    base_price: 219.00,
    portion_choices: ['Standard (32g Protein)', 'Athlete Mega (42g Protein, +₹50)'],
    ingredients: ['Fresh Paneer (150g)', 'Quinoa', 'Broccoli', 'Bell Peppers', 'Olive Oil', 'Tahini'],
    allergens: ['Dairy'],
    dietary_tags: ['Vegetarian', 'High-Protein', 'Balanced Bowls'],
    is_available: true,
    is_featured: true,
    is_tiffin_eligible: true,
    prep_time_minutes: 25,
    calories: 520,
    protein_grams: 32.0,
    carbs_grams: 38.0,
    fat_grams: 22.0,
    image_url: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    rating_count: 380
  },
  {
    id: 'meal_021',
    seller_id: 'seller_05',
    category_id: 'cat_06',
    name: 'Tender Grilled Chicken & Brown Rice Bowl (38g Protein)',
    slug: 'grilled-chicken-brown-rice-bowl',
    description: 'Char-grilled chicken breast glazed with smoked paprika and garlic herb marinade, served with brown basmati rice, steamed beans, and charred corn.',
    cuisine: 'Continental',
    base_price: 239.00,
    portion_choices: ['Standard (38g Protein)', 'Mega (48g Protein, +₹60)'],
    ingredients: ['Chicken Breast (180g)', 'Brown Basmati Rice', 'French Beans', 'Corn', 'Paprika', 'Garlic'],
    allergens: [],
    dietary_tags: ['Chicken and Fish Meals', 'High-Protein', 'Balanced Bowls'],
    is_available: true,
    is_featured: true,
    is_tiffin_eligible: true,
    prep_time_minutes: 25,
    calories: 510,
    protein_grams: 38.5,
    carbs_grams: 48.0,
    fat_grams: 8.5,
    image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    rating_count: 420
  },
  {
    id: 'meal_022',
    seller_id: 'seller_05',
    category_id: 'cat_06',
    name: 'Spiced Organic Tofu & Edamame Bowl (28g Protein)',
    slug: 'tofu-edamame-bowl',
    description: 'Crispy pan-fried organic tofu tossed in ginger sesame glaze, shelled edamame beans, ribbon carrots, and red rice.',
    cuisine: 'Asian',
    base_price: 199.00,
    portion_choices: ['Standard Bowl (400g)'],
    ingredients: ['Organic Tofu', 'Edamame', 'Red Rice', 'Carrot', 'Sesame Oil', 'Ginger', 'Tamari'],
    allergens: ['Soy'],
    dietary_tags: ['Vegan', 'High-Protein', 'Vegetarian'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: true,
    prep_time_minutes: 20,
    calories: 460,
    protein_grams: 28.0,
    carbs_grams: 44.0,
    fat_grams: 14.0,
    image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    rating_count: 145
  },
  {
    id: 'meal_023',
    seller_id: 'seller_05',
    category_id: 'cat_06',
    name: 'Four-Egg Scramble Box with Sautéed Greens (26g Protein)',
    slug: 'four-egg-scramble-greens',
    description: 'Two whole eggs and two egg whites scrambled with spring onions and black pepper. Served with buttered mushrooms and whole grain toast.',
    cuisine: 'Continental',
    base_price: 159.00,
    portion_choices: ['Box with 2 Multigrain Toasts'],
    ingredients: ['Farm Eggs', 'Button Mushrooms', 'Spinach', 'Multigrain Bread', 'Butter', 'Black Pepper'],
    allergens: ['Eggs', 'Dairy', 'Gluten'],
    dietary_tags: ['Egg Meals', 'High-Protein', 'Breakfast'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: true,
    prep_time_minutes: 15,
    calories: 380,
    protein_grams: 26.0,
    carbs_grams: 28.0,
    fat_grams: 14.0,
    image_url: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    rating_count: 165
  },

  // 7. Balanced Bowls (cat_07)
  {
    id: 'meal_024',
    seller_id: 'seller_05',
    category_id: 'cat_07',
    name: 'Millet & Dal Makhani Super Balanced Bowl',
    slug: 'millet-dal-makhani-bowl',
    description: 'Wholesome barnyard millet paired with a lighter homestyle black lentil dal, cucumber-tomato salad, and mint yogurt drizzle.',
    cuisine: 'North Indian',
    base_price: 169.00,
    portion_choices: ['Single Bowl (420g)'],
    ingredients: ['Barnyard Millet', 'Black Lentils', 'Tomato', 'Cucumber', 'Mint', 'Curd'],
    allergens: ['Dairy'],
    dietary_tags: ['Vegetarian', 'Balanced Bowls'],
    is_available: true,
    is_featured: true,
    is_tiffin_eligible: true,
    prep_time_minutes: 20,
    calories: 450,
    protein_grams: 17.0,
    carbs_grams: 62.0,
    fat_grams: 11.5,
    image_url: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    rating_count: 190
  },
  {
    id: 'meal_025',
    seller_id: 'seller_08',
    category_id: 'cat_07',
    name: 'Mediterranean Chickpea & Hummus Bowl',
    slug: 'mediterranean-chickpea-hummus-bowl',
    description: 'Spiced roasted chickpeas, silky garlic hummus, kalamata olives, pickled beetroot, crisp lettuce, and warm whole-wheat pita chips.',
    cuisine: 'Continental',
    base_price: 189.00,
    portion_choices: ['Regular Bowl (400g)'],
    ingredients: ['Chickpeas', 'Tahini', 'Garlic', 'Olives', 'Beetroot', 'Wheat Pita'],
    allergens: ['Gluten'],
    dietary_tags: ['Vegan', 'Balanced Bowls', 'Salads'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: false,
    prep_time_minutes: 15,
    calories: 420,
    protein_grams: 16.0,
    carbs_grams: 56.0,
    fat_grams: 14.0,
    image_url: 'https://images.unsplash.com/photo-1529059997568-3d847b1154f0?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    rating_count: 130
  },

  // 8. Vegetarian (cat_08)
  {
    id: 'meal_026',
    seller_id: 'seller_01',
    category_id: 'cat_08',
    name: 'Paneer Butter Masala with 3 Garlic Phulkas',
    slug: 'paneer-butter-masala-phulkas',
    description: 'Soft cottage cheese simmered in a mildly sweet, buttery tomato-cashew gravy with fenugreek. Served with 3 soft phulkas brushed with garlic butter.',
    cuisine: 'North Indian',
    base_price: 179.00,
    portion_choices: ['Standard (3 Rotis)', 'Hearty (4 Rotis)'],
    ingredients: ['Paneer', 'Cashews', 'Butter', 'Cream', 'Tomato', 'Wheat Flour', 'Garlic'],
    allergens: ['Dairy', 'Nuts', 'Gluten'],
    dietary_tags: ['Vegetarian', 'North Indian'],
    is_available: true,
    is_featured: true,
    is_tiffin_eligible: true,
    prep_time_minutes: 25,
    calories: 640,
    protein_grams: 22.0,
    carbs_grams: 68.0,
    fat_grams: 26.0,
    image_url: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    rating_count: 410
  },
  {
    id: 'meal_027',
    seller_id: 'seller_01',
    category_id: 'cat_08',
    name: 'Homestyle Bhindi Do Pyaza with 3 Phulkas',
    slug: 'bhindi-do-pyaza-phulkas',
    description: 'Tender fresh ladyfingers stir-fried with twin cuts of crunchy caramelized onions, carom seeds (ajwain), and tangy amchur.',
    cuisine: 'North Indian',
    base_price: 129.00,
    portion_choices: ['Standard (3 Rotis)'],
    ingredients: ['Ladyfinger (Okra)', 'Onion', 'Carom Seeds', 'Dried Mango Powder', 'Wheat Flour'],
    allergens: ['Gluten'],
    dietary_tags: ['Vegetarian', 'Vegan'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: true,
    prep_time_minutes: 20,
    calories: 390,
    protein_grams: 9.5,
    carbs_grams: 62.0,
    fat_grams: 9.0,
    image_url: '/images/meals/meal_027.jpg',
    rating: 4.7,
    rating_count: 112
  },

  // 9. Vegan (cat_09)
  {
    id: 'meal_028',
    seller_id: 'seller_06',
    category_id: 'cat_09',
    name: 'Spicy Tofu Tikka Masala with Brown Rice',
    slug: 'spicy-tofu-tikka-masala-brown-rice',
    description: '100% plant-based dairy-free delicacy: Marinated firm tofu cubes cooked in coconut milk and crushed tomato gravy. Served with organic brown rice.',
    cuisine: 'North Indian',
    base_price: 189.00,
    portion_choices: ['Standard Box (450g)'],
    ingredients: ['Firm Tofu', 'Coconut Milk', 'Tomato', 'Cumin', 'Brown Rice', 'Ginger'],
    allergens: ['Soy'],
    dietary_tags: ['Vegan', 'Vegetarian', 'High-Protein'],
    is_available: true,
    is_featured: true,
    is_tiffin_eligible: true,
    prep_time_minutes: 25,
    calories: 470,
    protein_grams: 22.0,
    carbs_grams: 56.0,
    fat_grams: 14.5,
    image_url: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    rating_count: 175
  },
  {
    id: 'meal_029',
    seller_id: 'seller_06',
    category_id: 'cat_09',
    name: 'Green Pea & Soya Chunk Curry with 3 Phulkas',
    slug: 'soya-chunk-green-pea-curry',
    description: 'Protein-packed textured soy chunks and sweet tender peas simmered in a homestyle onion-tomato gravy. Served with 3 whole wheat phulkas.',
    cuisine: 'North Indian',
    base_price: 135.00,
    portion_choices: ['Standard (3 Rotis)'],
    ingredients: ['Soya Chunks', 'Green Peas', 'Onion', 'Tomato', 'Wheat Flour', 'Garam Masala'],
    allergens: ['Soy', 'Gluten'],
    dietary_tags: ['Vegan', 'Vegetarian', 'High-Protein'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: true,
    prep_time_minutes: 20,
    calories: 440,
    protein_grams: 26.0,
    carbs_grams: 58.0,
    fat_grams: 7.5,
    image_url: 'https://images.unsplash.com/photo-1574484284002-952d92456975?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    rating_count: 88
  },

  // 10. Egg Meals (cat_10)
  {
    id: 'meal_030',
    seller_id: 'seller_02',
    category_id: 'cat_10',
    name: 'Dhaba Style Double Egg Curry with Jeera Rice',
    slug: 'dhaba-egg-curry-jeera-rice',
    description: 'Two golden-fried boiled eggs simmered in a robust, slow-cooked caramelized onion and rustic whole spice curry. Paired with aromatic cumin rice.',
    cuisine: 'North Indian',
    base_price: 149.00,
    portion_choices: ['Single Box (450g)'],
    ingredients: ['Farm Eggs (2)', 'Onion', 'Tomato', 'Basmati Rice', 'Cumin', 'Garam Masala'],
    allergens: ['Eggs'],
    dietary_tags: ['Egg Meals', 'High-Protein'],
    is_available: true,
    is_featured: true,
    is_tiffin_eligible: true,
    prep_time_minutes: 20,
    calories: 480,
    protein_grams: 19.5,
    carbs_grams: 58.0,
    fat_grams: 16.0,
    image_url: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    rating_count: 215
  },
  {
    id: 'meal_031',
    seller_id: 'seller_03',
    category_id: 'cat_10',
    name: 'Street Style Anda Bhurji with 3 Pavs',
    slug: 'anda-bhurji-pav-combo',
    description: 'Three farm eggs scrambled on high flame with finely chopped onions, juicy tomatoes, slit green chilies, and pav bhaji masala. Served with 3 buttered pavs.',
    cuisine: 'Maharashtrian',
    base_price: 125.00,
    portion_choices: ['Standard (3 Pavs)', 'Double Bhurji (+₹40)'],
    ingredients: ['Eggs (3)', 'Onion', 'Tomato', 'Pav Bread', 'Butter', 'Coriander'],
    allergens: ['Eggs', 'Gluten', 'Dairy'],
    dietary_tags: ['Egg Meals', 'High-Protein'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: false,
    prep_time_minutes: 15,
    calories: 520,
    protein_grams: 22.0,
    carbs_grams: 52.0,
    fat_grams: 21.0,
    image_url: '/images/meals/meal_031.jpg',
    rating: 4.8,
    rating_count: 180
  },

  // 11. Chicken and Fish Meals (cat_11)
  {
    id: 'meal_032',
    seller_id: 'seller_02',
    category_id: 'cat_11',
    name: 'Homestyle Chicken Curry with 3 Phulkas & Rice',
    slug: 'homestyle-chicken-curry-meal',
    description: 'Tender chicken pieces cooked in a comforting homestyle gravy of ground coriander, browned onions, and yogurt. Served with 3 rotis and a portion of rice.',
    cuisine: 'North Indian',
    base_price: 199.00,
    portion_choices: ['Standard Thali', 'Extra Chicken (+₹60)'],
    ingredients: ['Chicken', 'Onion', 'Tomato', 'Yogurt', 'Wheat Flour', 'Basmati Rice'],
    allergens: ['Dairy', 'Gluten'],
    dietary_tags: ['Chicken and Fish Meals', 'High-Protein'],
    is_available: true,
    is_featured: true,
    is_tiffin_eligible: true,
    prep_time_minutes: 25,
    calories: 590,
    protein_grams: 34.0,
    carbs_grams: 62.0,
    fat_grams: 17.0,
    image_url: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    rating_count: 340
  },
  {
    id: 'meal_033',
    seller_id: 'seller_04',
    category_id: 'cat_11',
    name: 'Malabar Fish Curry with Steamed Rice',
    slug: 'malabar-fish-curry-steamed-rice',
    description: 'Fresh local fish steaks gently poached in a tangy coconut and kudampuli (pot tamarind) curry with curry leaves and shallots. Served with hot steamed rice.',
    cuisine: 'South Indian',
    base_price: 229.00,
    portion_choices: ['Regular (450g Box)'],
    ingredients: ['Fish Fillet', 'Coconut Milk', 'Kudampuli', 'Shallots', 'Fenugreek', 'Rice'],
    allergens: ['Fish'],
    dietary_tags: ['Chicken and Fish Meals'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: true,
    prep_time_minutes: 25,
    calories: 510,
    protein_grams: 31.0,
    carbs_grams: 64.0,
    fat_grams: 12.5,
    image_url: '/images/meals/meal_033.jpg',
    rating: 4.8,
    rating_count: 145
  },

  // 12. Jain-Friendly Options (cat_12)
  {
    id: 'meal_034',
    seller_id: 'seller_06',
    category_id: 'cat_12',
    name: 'Jain Paneer Butter Masala with 3 Phulkas',
    slug: 'jain-paneer-butter-masala',
    description: 'Strictly prepared without onion, garlic, or root vegetables. Malai paneer cooked in a rich, velvety tomato, cashew, and melon seed gravy.',
    cuisine: 'North Indian',
    base_price: 179.00,
    portion_choices: ['Standard (3 Rotis)'],
    ingredients: ['Paneer', 'Tomato Puree', 'Cashews', 'Melon Seeds', 'Butter', 'Wheat Flour'],
    allergens: ['Dairy', 'Nuts', 'Gluten'],
    dietary_tags: ['Jain-Friendly Options', 'Vegetarian'],
    is_available: true,
    is_featured: true,
    is_tiffin_eligible: true,
    prep_time_minutes: 20,
    calories: 580,
    protein_grams: 21.0,
    carbs_grams: 54.0,
    fat_grams: 25.0,
    image_url: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    rating_count: 160
  },
  {
    id: 'meal_035',
    seller_id: 'seller_06',
    category_id: 'cat_12',
    name: 'Jain Moong Dal & Bottle Gourd (Lauki) Khichdi',
    slug: 'jain-moong-dal-lauki-khichdi',
    description: 'Digestive, soothing yellow lentil khichdi tempered with cumin and asafoetida (hing), cooked with soft bottle gourd cubes and pure cow ghee.',
    cuisine: 'North Indian',
    base_price: 119.00,
    portion_choices: ['Standard Bowl (400g)'],
    ingredients: ['Yellow Moong Dal', 'Rice', 'Bottle Gourd', 'Cumin', 'Hing', 'Ghee'],
    allergens: ['Dairy'],
    dietary_tags: ['Jain-Friendly Options', 'Vegetarian'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: true,
    prep_time_minutes: 20,
    calories: 390,
    protein_grams: 14.0,
    carbs_grams: 65.0,
    fat_grams: 7.5,
    image_url: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    rating_count: 125
  },

  // 13. Rice and Biryani (cat_13)
  {
    id: 'meal_036',
    seller_id: 'seller_02',
    category_id: 'cat_13',
    name: 'Awadhi Veg Dum Biryani with Burani Raita',
    slug: 'awadhi-veg-dum-biryani',
    description: 'Long grain basmati rice layered with marinated carrots, beans, cauliflower, and paneer cubes, infused with saffron, mint, and fried onions.',
    cuisine: 'North Indian',
    base_price: 179.00,
    portion_choices: ['Single Portion (500g)', 'Jumbo Pack (900g, +₹130)'],
    ingredients: ['Basmati Rice', 'Paneer', 'Carrot', 'Cauliflower', 'Saffron', 'Mint', 'Curd'],
    allergens: ['Dairy'],
    dietary_tags: ['Vegetarian', 'Rice and Biryani'],
    is_available: true,
    is_featured: true,
    is_tiffin_eligible: true,
    prep_time_minutes: 25,
    calories: 590,
    protein_grams: 18.0,
    carbs_grams: 88.0,
    fat_grams: 16.0,
    image_url: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    rating_count: 320
  },
  {
    id: 'meal_037',
    seller_id: 'seller_02',
    category_id: 'cat_13',
    name: 'Kolkata Style Chicken Biryani with Boiled Egg',
    slug: 'kolkata-chicken-biryani',
    description: 'Aromatic, subtly spiced rice cooked in chicken stock with a tender chicken thigh, seasoned soft potato, and a hard-boiled egg.',
    cuisine: 'North Indian',
    base_price: 239.00,
    portion_choices: ['Single Box (550g)'],
    ingredients: ['Chicken Thigh', 'Basmati Rice', 'Potato', 'Boiled Egg', 'Kewra Water', 'Ghee'],
    allergens: ['Eggs', 'Dairy'],
    dietary_tags: ['Chicken and Fish Meals', 'Rice and Biryani', 'High-Protein'],
    is_available: true,
    is_featured: true,
    is_tiffin_eligible: false,
    prep_time_minutes: 25,
    calories: 670,
    protein_grams: 36.0,
    carbs_grams: 84.0,
    fat_grams: 18.0,
    image_url: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    rating_count: 280
  },
  {
    id: 'meal_038',
    seller_id: 'seller_01',
    category_id: 'cat_13',
    name: 'Comforting Moong Dal Khichdi with Papad & Achar',
    slug: 'comforting-moong-dal-khichdi',
    description: 'The golden bowl of healing: Rice and yellow moong lentils simmered to perfection with cumin, ginger, and ghee. Accompanied by roasted papad and mango pickle.',
    cuisine: 'North Indian',
    base_price: 109.00,
    portion_choices: ['Standard (400g)'],
    ingredients: ['Rice', 'Moong Dal', 'Cumin', 'Ghee', 'Turmeric', 'Ginger'],
    allergens: ['Dairy'],
    dietary_tags: ['Vegetarian', 'Rice and Biryani'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: true,
    prep_time_minutes: 15,
    calories: 380,
    protein_grams: 13.0,
    carbs_grams: 66.0,
    fat_grams: 7.0,
    image_url: '/images/meals/meal_038.jpg',
    rating: 4.8,
    rating_count: 210
  },

  // 14. Roti and Sabzi (cat_14)
  {
    id: 'meal_039',
    seller_id: 'seller_01',
    category_id: 'cat_14',
    name: 'Aloo Methi Sukhi Sabzi with 4 Whole Wheat Phulkas',
    slug: 'aloo-methi-phulkas',
    description: 'Baby potatoes cooked with bitter-sweet fresh fenugreek leaves, roasted cumin, and dry mango powder. Served with 4 hot, oil-free whole wheat phulkas.',
    cuisine: 'North Indian',
    base_price: 115.00,
    portion_choices: ['Standard (4 Phulkas)'],
    ingredients: ['Potato', 'Fresh Fenugreek', 'Cumin', 'Wheat Flour', 'Mustard Oil'],
    allergens: ['Gluten'],
    dietary_tags: ['Vegetarian', 'Vegan', 'Roti and Sabzi'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: true,
    prep_time_minutes: 20,
    calories: 420,
    protein_grams: 11.0,
    carbs_grams: 76.0,
    fat_grams: 7.5,
    image_url: 'https://images.unsplash.com/photo-1567337710282-00832b415979?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    rating_count: 98
  },
  {
    id: 'meal_040',
    seller_id: 'seller_01',
    category_id: 'cat_14',
    name: 'Punjabi Baingan Bharta with 3 Parathas',
    slug: 'punjabi-baingan-bharta-parathas',
    description: 'Char-roasted smoked eggplant mashed and sautéed with pungent mustard oil, garlic, green chilies, and ripe tomatoes. Served with 3 whole wheat parathas.',
    cuisine: 'North Indian',
    base_price: 145.00,
    portion_choices: ['Standard (3 Parathas)'],
    ingredients: ['Eggplant (Aubergine)', 'Onion', 'Tomato', 'Garlic', 'Mustard Oil', 'Wheat Flour'],
    allergens: ['Gluten'],
    dietary_tags: ['Vegetarian', 'Vegan', 'Roti and Sabzi'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: true,
    prep_time_minutes: 25,
    calories: 510,
    protein_grams: 12.0,
    carbs_grams: 72.0,
    fat_grams: 17.5,
    image_url: '/images/meals/meal_040.jpg',
    rating: 4.8,
    rating_count: 142
  },

  // 15. Salads (cat_15)
  {
    id: 'meal_041',
    seller_id: 'seller_08',
    category_id: 'cat_15',
    name: 'Sprouted Moong & Pomegranate Protein Crunch',
    slug: 'sprouted-moong-pomegranate-salad',
    description: 'Crunchy sprouted green gram tossed with sweet pomegranate arils, diced cucumber, tomatoes, green chilies, chaat masala, and a zesty lemon squeeze.',
    cuisine: 'Indian',
    base_price: 119.00,
    portion_choices: ['350g Salad Bowl'],
    ingredients: ['Sprouted Moong', 'Pomegranate', 'Cucumber', 'Tomato', 'Chaat Masala', 'Lemon Juice'],
    allergens: [],
    dietary_tags: ['Vegetarian', 'Vegan', 'Salads', 'High-Protein'],
    is_available: true,
    is_featured: true,
    is_tiffin_eligible: false,
    prep_time_minutes: 10,
    calories: 220,
    protein_grams: 14.0,
    carbs_grams: 38.0,
    fat_grams: 2.0,
    image_url: 'https://images.unsplash.com/photo-1607532941433-304659e8198a?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    rating_count: 185
  },
  {
    id: 'meal_042',
    seller_id: 'seller_08',
    category_id: 'cat_15',
    name: 'Quinoa Greek Fiesta Salad with Feta',
    slug: 'quinoa-greek-fiesta-salad',
    description: 'Fluffy Peruvian quinoa, cherry tomatoes, English cucumber, kalamata olives, bell peppers, and crumbled Greek feta cheese in extra virgin olive oil vinaigrette.',
    cuisine: 'Continental',
    base_price: 199.00,
    portion_choices: ['400g Bowl'],
    ingredients: ['Quinoa', 'Feta Cheese', 'Cherry Tomatoes', 'Olives', 'Cucumber', 'Olive Oil'],
    allergens: ['Dairy'],
    dietary_tags: ['Vegetarian', 'Salads'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: false,
    prep_time_minutes: 15,
    calories: 360,
    protein_grams: 13.5,
    carbs_grams: 42.0,
    fat_grams: 16.0,
    image_url: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    rating_count: 120
  },

  // 16. Wraps and Sandwiches (cat_16)
  {
    id: 'meal_043',
    seller_id: 'seller_08',
    category_id: 'cat_16',
    name: 'Whole-Wheat Paneer Tikka Kathi Wrap',
    slug: 'whole-wheat-paneer-tikka-wrap',
    description: 'Tandoori spiced cottage cheese chunks rolled in a 100% whole wheat paratha with crisp mint onion relish and a light yogurt spread.',
    cuisine: 'North Indian',
    base_price: 149.00,
    portion_choices: ['Single Wrap', '2 Wraps Combo (+₹110)'],
    ingredients: ['Whole Wheat Flour', 'Paneer', 'Mint Yogurt', 'Onion', 'Bell Peppers', 'Chaat Masala'],
    allergens: ['Dairy', 'Gluten'],
    dietary_tags: ['Vegetarian', 'Wraps and Sandwiches'],
    is_available: true,
    is_featured: true,
    is_tiffin_eligible: false,
    prep_time_minutes: 15,
    calories: 420,
    protein_grams: 18.0,
    carbs_grams: 48.0,
    fat_grams: 16.5,
    image_url: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    rating_count: 220
  },
  {
    id: 'meal_044',
    seller_id: 'seller_08',
    category_id: 'cat_16',
    name: 'Grilled Herb Chicken & Avocado Club Sandwich',
    slug: 'grilled-chicken-avocado-sandwich',
    description: 'Shredded roasted chicken breast, hass avocado spread, sliced tomatoes, and crisp lettuce between three toasted multigrain bread slices.',
    cuisine: 'Continental',
    base_price: 189.00,
    portion_choices: ['3-Layer Multigrain Sandwich'],
    ingredients: ['Chicken Breast', 'Avocado', 'Multigrain Bread', 'Lettuce', 'Tomato', 'Dijon Mustard'],
    allergens: ['Gluten'],
    dietary_tags: ['Chicken and Fish Meals', 'Wraps and Sandwiches', 'High-Protein'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: false,
    prep_time_minutes: 15,
    calories: 460,
    protein_grams: 28.0,
    carbs_grams: 44.0,
    fat_grams: 15.0,
    image_url: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    rating_count: 195
  },

  // 17. Snacks (cat_17)
  {
    id: 'meal_045',
    seller_id: 'seller_08',
    category_id: 'cat_17',
    name: 'Roasted Peri-Peri Makhana (Foxnuts 100g)',
    slug: 'roasted-peri-peri-makhana',
    description: 'Crispy lotus seeds roasted in olive oil with zesty peri-peri spice dust. Low-calorie, gluten-free, guilt-free evening munching.',
    cuisine: 'Indian',
    base_price: 89.00,
    portion_choices: ['100g Pack'],
    ingredients: ['Foxnuts (Makhana)', 'Olive Oil', 'Peri Peri Spice', 'Pink Himalayan Salt'],
    allergens: [],
    dietary_tags: ['Vegetarian', 'Vegan', 'Snacks'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: false,
    prep_time_minutes: 5,
    calories: 180,
    protein_grams: 5.0,
    carbs_grams: 34.0,
    fat_grams: 3.5,
    image_url: 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    rating_count: 75
  },
  {
    id: 'meal_046',
    seller_id: 'seller_03',
    category_id: 'cat_17',
    name: 'Sabudana Vada (2 Pcs) with Sweet Curd & Chutney',
    slug: 'sabudana-vada-sweet-curd',
    description: 'Crispy golden sago and crushed peanut patties infused with green chilies and cumin. Served with chilled sweet curd and peanut chutney.',
    cuisine: 'Maharashtrian',
    base_price: 99.00,
    portion_choices: ['2 Pieces'],
    ingredients: ['Tapioca Pearls', 'Roasted Peanuts', 'Potato', 'Green Chili', 'Curd', 'Cumin'],
    allergens: ['Peanuts', 'Dairy'],
    dietary_tags: ['Vegetarian', 'Snacks'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: false,
    prep_time_minutes: 15,
    calories: 360,
    protein_grams: 6.0,
    carbs_grams: 48.0,
    fat_grams: 16.0,
    image_url: '/images/meals/meal_046.jpg',
    rating: 4.8,
    rating_count: 140
  },

  // 18. Family Combos (cat_18)
  {
    id: 'meal_047',
    seller_id: 'seller_07',
    category_id: 'cat_18',
    name: 'Grand Royal North Indian Family Thali (Serves 4)',
    slug: 'grand-royal-north-indian-family-thali',
    description: 'Complete family banquet: 12 soft butter phulkas, Dal Makhani (500ml), Paneer Butter Masala (500ml), Mix Veg Sabzi (350ml), Jeera Rice (600g), Boondi Raita, Gulab Jamun (4 pcs), and Salad.',
    cuisine: 'North Indian',
    base_price: 599.00,
    portion_choices: ['Family Pack (Serves 3-4)'],
    ingredients: ['Paneer', 'Black Lentils', 'Mixed Vegetables', 'Basmati Rice', 'Wheat Flour', 'Butter', 'Mawa'],
    allergens: ['Dairy', 'Gluten', 'Nuts'],
    dietary_tags: ['Vegetarian', 'Family Combos'],
    is_available: true,
    is_featured: true,
    is_tiffin_eligible: false,
    prep_time_minutes: 35,
    calories: 2200,
    protein_grams: 82.0,
    carbs_grams: 280.0,
    fat_grams: 88.0,
    image_url: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    rating_count: 480
  },
  {
    id: 'meal_048',
    seller_id: 'seller_07',
    category_id: 'cat_18',
    name: 'Weekend Dum Biryani Family Feast (Serves 4)',
    slug: 'weekend-dum-biryani-family-feast',
    description: '1.2kg fragrant Veg Dum Biryani, 4 crispy mirchi salans, large pot of creamy cucumber-mint raita, and 4 portions of royal Angoori Jamun.',
    cuisine: 'North Indian',
    base_price: 549.00,
    portion_choices: ['Family Feast (Serves 4)'],
    ingredients: ['Basmati Rice', 'Paneer', 'Green Peas', 'Yogurt', 'Saffron', 'Mint', 'Fried Onions'],
    allergens: ['Dairy'],
    dietary_tags: ['Vegetarian', 'Family Combos', 'Rice and Biryani'],
    is_available: true,
    is_featured: true,
    is_tiffin_eligible: false,
    prep_time_minutes: 35,
    calories: 1950,
    protein_grams: 64.0,
    carbs_grams: 290.0,
    fat_grams: 62.0,
    image_url: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    rating_count: 295
  },
  {
    id: 'meal_049',
    seller_id: 'seller_07',
    category_id: 'cat_18',
    name: 'Roti-Sabzi Everyday Family Bundle (Serves 3)',
    slug: 'roti-sabzi-family-bundle',
    description: '10 fresh whole wheat chapati/phulkas, comforting Yellow Dal Tadka (450ml), Seasonal Aloo Gobhi Sabzi (400ml), and homemade roasted papad pack.',
    cuisine: 'North Indian',
    base_price: 389.00,
    portion_choices: ['Family Pack (Serves 3)'],
    ingredients: ['Wheat Flour', 'Toor Dal', 'Cauliflower', 'Potato', 'Cumin', 'Tomatoes'],
    allergens: ['Gluten'],
    dietary_tags: ['Vegetarian', 'Family Combos', 'Everyday Tiffins'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: false,
    prep_time_minutes: 30,
    calories: 1450,
    protein_grams: 48.0,
    carbs_grams: 230.0,
    fat_grams: 38.0,
    image_url: 'https://images.unsplash.com/photo-1625398407796-82650a8c135f?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    rating_count: 210
  },

  // 19. Beverages (cat_19)
  {
    id: 'meal_050',
    seller_id: 'seller_01',
    category_id: 'cat_19',
    name: 'Masala Buttermilk (Chaas) with Mint & Cumin',
    slug: 'masala-buttermilk-chaas',
    description: 'Cooling churned curd beverage infused with roasted cumin powder, fresh crushed mint leaves, ginger, and black salt. Zero artificial flavors.',
    cuisine: 'Indian',
    base_price: 35.00,
    portion_choices: ['300ml Bottle'],
    ingredients: ['Curd', 'Water', 'Roasted Cumin', 'Mint', 'Black Salt', 'Ginger'],
    allergens: ['Dairy'],
    dietary_tags: ['Vegetarian', 'Beverages'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: true,
    prep_time_minutes: 5,
    calories: 65,
    protein_grams: 3.5,
    carbs_grams: 5.0,
    fat_grams: 2.2,
    image_url: 'https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    rating_count: 380
  },
  {
    id: 'meal_051',
    seller_id: 'seller_08',
    category_id: 'cat_19',
    name: 'Fresh Cold-Pressed ABC Glow Juice (Apple, Beetroot, Carrot)',
    slug: 'abc-glow-juice',
    description: '100% natural, raw, no added sugar, cold-pressed juice of crisp Himachal apples, sweet carrots, and ruby beetroots with a dash of ginger.',
    cuisine: 'Continental',
    base_price: 99.00,
    portion_choices: ['300ml Bottle'],
    ingredients: ['Apple', 'Beetroot', 'Carrot', 'Ginger', 'Lemon'],
    allergens: [],
    dietary_tags: ['Vegetarian', 'Vegan', 'Beverages'],
    is_available: true,
    is_featured: true,
    is_tiffin_eligible: false,
    prep_time_minutes: 5,
    calories: 120,
    protein_grams: 1.5,
    carbs_grams: 28.0,
    fat_grams: 0.2,
    image_url: '/images/meals/meal_051.jpg',
    rating: 4.8,
    rating_count: 160
  },
  {
    id: 'meal_052',
    seller_id: 'seller_04',
    category_id: 'cat_19',
    name: 'Authentic South Indian Degree Filter Coffee',
    slug: 'degree-filter-coffee',
    description: 'Brewed chicory-blend decoction frothed with boiling whole milk and brown sugar. Delivered in an insulated takeaway flask.',
    cuisine: 'South Indian',
    base_price: 49.00,
    portion_choices: ['200ml Flask'],
    ingredients: ['Coffee Beans', 'Chicory', 'Milk', 'Raw Sugar'],
    allergens: ['Dairy'],
    dietary_tags: ['Vegetarian', 'Beverages'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: false,
    prep_time_minutes: 10,
    calories: 95,
    protein_grams: 3.0,
    carbs_grams: 12.0,
    fat_grams: 3.5,
    image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    rating_count: 230
  },

  // 20. Desserts (cat_20)
  {
    id: 'meal_053',
    seller_id: 'seller_01',
    category_id: 'cat_20',
    name: 'Slow-Cooked Dry Fruit Rice Kheer',
    slug: 'dry-fruit-rice-kheer',
    description: 'Fragrant basmati rice slow-simmered in reduced cardamom milk, sweetened with organic jaggery, garnished with toasted pistachios and almonds.',
    cuisine: 'North Indian',
    base_price: 79.00,
    portion_choices: ['150ml Cup'],
    ingredients: ['Milk', 'Basmati Rice', 'Cardamom', 'Jaggery', 'Almonds', 'Pistachios'],
    allergens: ['Dairy', 'Nuts'],
    dietary_tags: ['Vegetarian', 'Desserts'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: true,
    prep_time_minutes: 10,
    calories: 210,
    protein_grams: 5.5,
    carbs_grams: 34.0,
    fat_grams: 6.0,
    image_url: '/images/meals/meal_053.jpg',
    rating: 4.8,
    rating_count: 185
  },
  {
    id: 'meal_054',
    seller_id: 'seller_03',
    category_id: 'cat_20',
    name: 'Maharashtrian Puran Poli with Desi Ghee (2 Pcs)',
    slug: 'puran-poli-desi-ghee',
    description: 'Traditional sweet flatbread stuffed with spiced chana dal and nutmeg-cardamom jaggery, pan-roasted in rich desi ghee.',
    cuisine: 'Maharashtrian',
    base_price: 99.00,
    portion_choices: ['2 Pieces'],
    ingredients: ['Chana Dal', 'Jaggery', 'Cardamom', 'Nutmeg', 'Wheat Flour', 'Ghee'],
    allergens: ['Gluten', 'Dairy'],
    dietary_tags: ['Vegetarian', 'Desserts'],
    is_available: true,
    is_featured: true,
    is_tiffin_eligible: true,
    prep_time_minutes: 15,
    calories: 340,
    protein_grams: 8.0,
    carbs_grams: 58.0,
    fat_grams: 9.0,
    image_url: '/images/meals/meal_054.jpg',
    rating: 4.9,
    rating_count: 220
  },

  // Additional variety to cross 60+ distinct meals:
  {
    id: 'meal_055',
    seller_id: 'seller_01',
    category_id: 'cat_02',
    name: 'Kadhi Pakora with Steamed Rice Box',
    slug: 'kadhi-pakora-steamed-rice',
    description: 'Spiced yogurt and gram flour kadhi with crispy onion pakoras, tempered with fenugreek seeds and dry red chili. Served with steamed basmati rice.',
    cuisine: 'North Indian',
    base_price: 119.00,
    portion_choices: ['Standard (450g Box)'],
    ingredients: ['Curd', 'Gram Flour', 'Onion', 'Rice', 'Fenugreek Seeds', 'Mustard Seeds'],
    allergens: ['Dairy'],
    dietary_tags: ['Vegetarian', 'Everyday Tiffins'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: true,
    prep_time_minutes: 20,
    calories: 460,
    protein_grams: 14.0,
    carbs_grams: 72.0,
    fat_grams: 12.0,
    image_url: 'https://images.unsplash.com/photo-1574653853027-5382a3d23a15?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    rating_count: 145
  },
  {
    id: 'meal_056',
    seller_id: 'seller_05',
    category_id: 'cat_06',
    name: 'Soya & Sprouts High-Fiber Protein Bowl (30g Protein)',
    slug: 'soya-sprouts-protein-bowl',
    description: 'High-protein soya chunks stir-fried with mixed sprouts, bell peppers, zucchini, and roasted peanuts in a lemon-pepper drizzle.',
    cuisine: 'Indian',
    base_price: 179.00,
    portion_choices: ['Standard (400g)'],
    ingredients: ['Soya Chunks', 'Mixed Sprouts', 'Bell Peppers', 'Peanuts', 'Lemon', 'Black Pepper'],
    allergens: ['Soy', 'Peanuts'],
    dietary_tags: ['Vegan', 'High-Protein', 'Balanced Bowls'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: true,
    prep_time_minutes: 20,
    calories: 410,
    protein_grams: 30.0,
    carbs_grams: 42.0,
    fat_grams: 10.0,
    image_url: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    rating_count: 110
  },
  {
    id: 'meal_057',
    seller_id: 'seller_02',
    category_id: 'cat_03',
    name: 'Paneer Lababdar with 3 Whole Wheat Phulkas',
    slug: 'paneer-lababdar-phulkas',
    description: 'Grated and cubed paneer cooked in an onion-tomato gravy flavored with ginger juliennes, green chilies, and cream. Served with 3 soft phulkas.',
    cuisine: 'North Indian',
    base_price: 185.00,
    portion_choices: ['Standard (3 Rotis)'],
    ingredients: ['Paneer', 'Tomato', 'Onion', 'Ginger', 'Wheat Flour', 'Cream'],
    allergens: ['Dairy', 'Gluten'],
    dietary_tags: ['Vegetarian', 'North Indian'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: true,
    prep_time_minutes: 25,
    calories: 610,
    protein_grams: 23.0,
    carbs_grams: 64.0,
    fat_grams: 24.5,
    image_url: '/images/meals/meal_057.jpg',
    rating: 4.8,
    rating_count: 195
  },
  {
    id: 'meal_058',
    seller_id: 'seller_03',
    category_id: 'cat_05',
    name: 'Kothimbir Vadi (4 Pcs) with Green Chutney',
    slug: 'kothimbir-vadi-green-chutney',
    description: 'Steamed and crisp pan-fried savory cakes made of fresh coriander leaves, gram flour, sesame seeds, and mild green chili paste.',
    cuisine: 'Maharashtrian',
    base_price: 89.00,
    portion_choices: ['4 Pieces'],
    ingredients: ['Fresh Coriander', 'Gram Flour', 'Sesame Seeds', 'Green Chili', 'Lemon'],
    allergens: ['Sesame'],
    dietary_tags: ['Vegetarian', 'Vegan', 'Snacks'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: false,
    prep_time_minutes: 15,
    calories: 260,
    protein_grams: 8.5,
    carbs_grams: 34.0,
    fat_grams: 9.5,
    image_url: '/images/meals/meal_058.jpg',
    rating: 4.9,
    rating_count: 170
  },
  {
    id: 'meal_059',
    seller_id: 'seller_06',
    category_id: 'cat_12',
    name: 'Jain Matar Paneer with 3 Phulkas',
    slug: 'jain-matar-paneer-phulkas',
    description: 'Sweet green peas and soft cottage cheese simmered in a mildly spiced tomato-cashew curry without root vegetables. Served with 3 whole-wheat phulkas.',
    cuisine: 'North Indian',
    base_price: 169.00,
    portion_choices: ['Standard (3 Rotis)'],
    ingredients: ['Paneer', 'Green Peas', 'Tomato', 'Cashews', 'Wheat Flour', 'Ghee'],
    allergens: ['Dairy', 'Nuts', 'Gluten'],
    dietary_tags: ['Jain-Friendly Options', 'Vegetarian'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: true,
    prep_time_minutes: 20,
    calories: 520,
    protein_grams: 19.5,
    carbs_grams: 56.0,
    fat_grams: 21.0,
    image_url: '/images/meals/meal_059.jpg',
    rating: 4.7,
    rating_count: 110
  },
  {
    id: 'meal_060',
    seller_id: 'seller_04',
    category_id: 'cat_04',
    name: 'Medu Vada (3 Pcs) with Sambar & Coconut Chutney',
    slug: 'medu-vada-sambar-combo',
    description: 'Crisp golden lentil fritters with a fluffy interior, spiked with crushed black peppercorns, ginger, and curry leaves. Accompanied by piping hot sambar.',
    cuisine: 'South Indian',
    base_price: 95.00,
    portion_choices: ['3 Pieces'],
    ingredients: ['Urad Dal', 'Black Pepper', 'Curry Leaves', 'Ginger', 'Grated Coconut'],
    allergens: ['Dairy'],
    dietary_tags: ['Vegetarian', 'Breakfast'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: false,
    prep_time_minutes: 15,
    calories: 380,
    protein_grams: 11.0,
    carbs_grams: 44.0,
    fat_grams: 18.0,
    image_url: '/images/meals/meal_060.jpg',
    rating: 4.8,
    rating_count: 215
  },
  {
    id: 'meal_061',
    seller_id: 'seller_05',
    category_id: 'cat_06',
    name: 'Grilled Fish & Herb Couscous Bowl (34g Protein)',
    slug: 'grilled-fish-herb-couscous-bowl',
    description: 'Catch of the day fish fillet marinated in lemon dill butter and grilled to golden tenderness. Served with whole wheat couscous and grilled zucchini.',
    cuisine: 'Continental',
    base_price: 249.00,
    portion_choices: ['Standard (400g)'],
    ingredients: ['Fish Fillet', 'Couscous', 'Zucchini', 'Olive Oil', 'Dill', 'Lemon'],
    allergens: ['Fish', 'Gluten'],
    dietary_tags: ['Chicken and Fish Meals', 'High-Protein', 'Balanced Bowls'],
    is_available: true,
    is_featured: true,
    is_tiffin_eligible: true,
    prep_time_minutes: 25,
    calories: 470,
    protein_grams: 34.0,
    carbs_grams: 46.0,
    fat_grams: 11.0,
    image_url: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    rating_count: 165
  },
  {
    id: 'meal_062',
    seller_id: 'seller_07',
    category_id: 'cat_18',
    name: 'South Indian Feast Combo (Serves 3)',
    slug: 'south-indian-feast-combo',
    description: 'Traditional celebration meal: 6 fluffy idlis, 3 medu vadas, 1 large pot of vegetable sambar (750ml), coconut chutney, tomato chutney, and filter coffee flask.',
    cuisine: 'South Indian',
    base_price: 349.00,
    portion_choices: ['Family Tiffin (Serves 3)'],
    ingredients: ['Rice', 'Urad Dal', 'Lentils', 'Drumstick', 'Coconut', 'Curd'],
    allergens: ['Dairy'],
    dietary_tags: ['Vegetarian', 'Family Combos', 'Breakfast'],
    is_available: true,
    is_featured: false,
    is_tiffin_eligible: false,
    prep_time_minutes: 25,
    calories: 1250,
    protein_grams: 38.0,
    carbs_grams: 185.0,
    fat_grams: 36.0,
    image_url: 'https://images.unsplash.com/photo-1630383249896-424e482df921?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    rating_count: 140
  }
];
